[package]
name = "oligoscreen_differential"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31"
egui = "0.31"
bio = "2"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"
mimalloc = "0.1"
once_cell = "1"
